### ISSUE TITLE
Bug in lovers

### ISSUE THREAD

**Issue by Zashekago** [DashaPapicheva/Tea-website#3]
https://github.com/DashaPapicheva/Tea-website/blob/master/main.html#L157
https://github.com/DashaPapicheva/Tea-website/blob/master/main.html#L169

Need fix fullscreen view.

**Comment by DashaPapicheva** [comment]
Fixed

https://github.com/DashaPapicheva/Tea-website/blob/a687dbe8dba74dda525511fbad113e7ce9ed1d85/teaStyle.css#L282

**Comment by DashaPapicheva** [comment]
Fixed

https://github.com/DashaPapicheva/Tea-website/blob/a687dbe8dba74dda525511fbad113e7ce9ed1d85/teaStyle.css#L282
